# Generated by Django 4.0 on 2022-01-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Grupo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Periodo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Nickname', models.CharField(max_length=50, unique=True)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, unique=True)),
                ('Simbolo', models.CharField(max_length=3, unique=True)),
                ('No_Atomico', models.IntegerField(unique=True)),
                ('Masa_Atomica', models.FloatField()),
                ('Densidad', models.FloatField()),
                ('Informacion', models.CharField(blank=True, max_length=500, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.categoria')),
                ('Creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.user')),
                ('Grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.grupo')),
                ('Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.periodo')),
            ],
        ),
    ]
